# Generated by Django 4.2.30 on 2026-09-21 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaQueja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80, unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=200)),
                ('solucion_rapida', models.TextField(blank=True, help_text='Respuesta sugerida que resuelve el caso sin escalamiento (RN-11).', verbose_name='solución rápida')),
                ('activa', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'categoría de queja',
                'verbose_name_plural': 'categorías de queja',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Queja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consecutivo', models.CharField(blank=True, db_index=True, max_length=20, unique=True)),
                ('anonima', models.BooleanField(default=False, help_text='La identidad se oculta al gestor (RN-09).')),
                ('asunto', models.CharField(max_length=150)),
                ('descripcion', models.TextField()),
                ('evidencia', models.FileField(blank=True, null=True, upload_to='quejas/')),
                ('estado', models.CharField(choices=[('ABIERTO', 'Abierto'), ('EN_PROCESO', 'En proceso'), ('ESCALADO', 'Escalado al departamento'), ('RESUELTO', 'Resuelto'), ('CERRADO', 'Cerrado por el usuario')], default='ABIERTO', max_length=10)),
                ('prioridad', models.CharField(choices=[('BAJA', 'Baja'), ('MEDIA', 'Media'), ('ALTA', 'Alta')], default='MEDIA', max_length=5)),
                ('solucion', models.TextField(blank=True)),
                ('creada', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actualizada', models.DateTimeField(auto_now=True)),
                ('escalada', models.DateTimeField(blank=True, null=True)),
                ('resuelta', models.DateTimeField(blank=True, null=True)),
                ('confirmada_por_usuario', models.BooleanField(default=False)),
                ('satisfaccion', models.PositiveSmallIntegerField(blank=True, help_text='1 a 5 (RF-42).', null=True)),
            ],
            options={
                'verbose_name': 'queja',
                'verbose_name_plural': 'quejas',
                'ordering': ['-creada'],
            },
        ),
        migrations.CreateModel(
            name='Seguimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ASIGNACION', 'Asignación'), ('AVANCE', 'Avance'), ('SOLUCION', 'Solución'), ('REAPERTURA', 'Reapertura'), ('CIERRE', 'Cierre'), ('ESCALAMIENTO', 'Escalamiento')], default='AVANCE', max_length=12)),
                ('detalle', models.TextField()),
                ('creado', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'seguimiento',
                'verbose_name_plural': 'seguimientos',
                'ordering': ['creado'],
            },
        ),
    ]
