# Generated by Django 4.2.30 on 2026-09-21 02:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('materias', '0002_initial'),
        ('quejas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='seguimiento',
            name='autor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seguimientos_queja', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='seguimiento',
            name='queja',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seguimientos', to='quejas.queja'),
        ),
        migrations.AddField(
            model_name='queja',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quejas', to='quejas.categoriaqueja'),
        ),
        migrations.AddField(
            model_name='queja',
            name='gestor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quejas_gestionadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='queja',
            name='materia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quejas', to='materias.materia'),
        ),
        migrations.AddField(
            model_name='queja',
            name='radicada_por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quejas', to=settings.AUTH_USER_MODEL),
        ),
    ]
