# Generated by Django 4.2.30 on 2026-10-02 21:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('tipo', models.CharField(choices=[('SEMILLERO', 'Semillero de investigación'), ('GRUPO', 'Grupo de investigación')], db_index=True, default='SEMILLERO', max_length=12)),
                ('descripcion', models.TextField(blank=True, help_text='Objetivos, líneas de trabajo y forma de participación.')),
                ('linea', models.CharField(blank=True, help_text='Ej.: Inteligencia Artificial, Redes, Software.', max_length=150, verbose_name='línea de investigación')),
                ('cupo', models.PositiveSmallIntegerField(blank=True, help_text='Máximo de miembros. Vacío = sin límite.', null=True)),
                ('activo', models.BooleanField(db_index=True, default=True, help_text='Desactívalo para dejar de recibir solicitudes sin borrar el grupo.')),
                ('creado', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('coordinador', models.ForeignKey(blank=True, help_text='Docente que aprueba o rechaza las solicitudes.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grupos_coordinados', to=settings.AUTH_USER_MODEL)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grupos_creados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'grupo de investigación',
                'verbose_name_plural': 'grupos de investigación',
                'ordering': ['-creado', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='Inscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('ACEPTADA', 'Aceptada'), ('RECHAZADA', 'Rechazada'), ('CANCELADA', 'Cancelada por el usuario')], db_index=True, default='PENDIENTE', max_length=10)),
                ('respuesta', models.TextField(blank=True, help_text='Motivo o comentario para el coordinador.')),
                ('creada', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('respondida', models.DateTimeField(blank=True, null=True)),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones', to='investigacion.grupo')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones_grupo', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'inscripción a grupo',
                'verbose_name_plural': 'inscripciones a grupos',
                'ordering': ['-creada', '-pk'],
            },
        ),
        migrations.AddConstraint(
            model_name='inscripcion',
            constraint=models.UniqueConstraint(fields=('grupo', 'usuario'), name='uniq_inscripcion_grupo_usuario'),
        ),
    ]
