# Generated by Django 4.2.30 on 2026-09-21 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=12, unique=True, verbose_name='código')),
                ('nombre', models.CharField(max_length=120, verbose_name='nombre')),
                ('creditos', models.PositiveSmallIntegerField(default=3, verbose_name='créditos')),
                ('cupo_maximo', models.PositiveSmallIntegerField(default=30, verbose_name='cupo máximo')),
                ('estado', models.CharField(choices=[('PROPUESTA', 'Propuesta'), ('EN_REVISION', 'En revisión'), ('APROBADA', 'Aprobada'), ('RECHAZADA', 'Rechazada'), ('PUBLICADA', 'Publicada')], default='PROPUESTA', max_length=12, verbose_name='estado')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'materia',
                'verbose_name_plural': 'materias',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='SolicitudMateria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('CREACION', 'Creación'), ('EDICION', 'Edición')], max_length=10)),
                ('justificacion', models.TextField()),
                ('propuesta', models.JSONField(blank=True, default=dict, verbose_name='propuesta de cambios')),
                ('estado', models.CharField(choices=[('PROPUESTA', 'Propuesta'), ('EN_REVISION', 'En revisión'), ('APROBADA', 'Aprobada'), ('RECHAZADA', 'Rechazada'), ('PUBLICADA', 'Publicada')], default='PROPUESTA', max_length=12)),
                ('comentario_revision', models.TextField(blank=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('resuelta', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'solicitud de materia',
                'verbose_name_plural': 'solicitudes de materia',
                'ordering': ['-creado'],
            },
        ),
        migrations.CreateModel(
            name='VersionMateria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField(default=1, verbose_name='versión')),
                ('contenido', models.TextField(verbose_name='contenido / justificación')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'versión de materia',
                'verbose_name_plural': 'versiones de materia',
                'ordering': ['materia', '-version'],
            },
        ),
    ]
