# Generated by Django 4.2.30 on 2026-09-21 02:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('materias', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='versionmateria',
            name='autor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='versiones_materia', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='versionmateria',
            name='materia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versiones', to='materias.materia'),
        ),
        migrations.AddField(
            model_name='solicitudmateria',
            name='materia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes', to='materias.materia'),
        ),
        migrations.AddField(
            model_name='solicitudmateria',
            name='revisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revisiones_materia', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='solicitudmateria',
            name='solicitante',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_materia', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='materia',
            name='docentes',
            field=models.ManyToManyField(blank=True, limit_choices_to={'rol': 'DOCENTE'}, related_name='materias_dictadas', to=settings.AUTH_USER_MODEL, verbose_name='docentes asignados'),
        ),
        migrations.AddField(
            model_name='materia',
            name='prerrequisitos',
            field=models.ManyToManyField(blank=True, related_name='prerrequisito_de', to='materias.materia'),
        ),
    ]
