# Generated by Django 4.2.30 on 2026-09-22 22:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('materias', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='materia',
            name='semestre',
            field=models.PositiveSmallIntegerField(default=1, help_text='Semestre (1-10) en que se cursa según la malla curricular.', verbose_name='semestre del plan'),
        ),
        migrations.CreateModel(
            name='MallaCurricular',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semestre', models.PositiveSmallIntegerField(default=1, help_text='Semestre (1-10) en que el estudiante cursa esta materia.', verbose_name='semestre del plan')),
                ('estado', models.CharField(blank=True, choices=[('', 'Automático (derivado de inscripciones)'), ('PENDIENTE', 'Pendiente (sin ver)'), ('EN_CURSO', 'En curso (viendo)'), ('VISTA', 'Vista (ya cursada)')], default='', help_text='Vacío = derivado de las inscripciones del estudiante.', max_length=10, verbose_name='estado')),
                ('observacion', models.CharField(blank=True, max_length=200, verbose_name='observación')),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('actualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='malla_editada', to=settings.AUTH_USER_MODEL, verbose_name='última edición por')),
                ('estudiante', models.ForeignKey(limit_choices_to={'rol': 'ESTUDIANTE'}, on_delete=django.db.models.deletion.CASCADE, related_name='malla_curricular', to=settings.AUTH_USER_MODEL, verbose_name='estudiante')),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='malla_curricular', to='materias.materia', verbose_name='materia')),
            ],
            options={
                'verbose_name': 'malla curricular',
                'verbose_name_plural': 'mallas curriculares',
                'ordering': ['semestre', 'materia__codigo'],
                'unique_together': {('estudiante', 'materia')},
            },
        ),
    ]
