# Configuración de despliegue para Render
# https://render.com/docs/deploy-django
# Importa este servicio seleccionando "Blueprint" y conecta tu repo GitHub

services:
  - type: web
    name: sgdic-web
    runtime: python
    plan: free
    buildCommand: ./build.sh
    startCommand: ./start.sh
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: sgdic.settings
      - key: PYTHON_VERSION
        value: 3.12
      - key: SGDIC_DEBUG
        value: "0"
      - key: SGDIC_SECRET_KEY
        fromSecret: SGDIC_SECRET_KEY
      - key: DATABASE_URL
        fromDatabase: sgdic-db

databases:
  - name: sgdic-db
    region: oregon
    plan: free
    postgresVersion: "16"
