# Generated by Django 4.2.30 on 2026-09-21 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditoriaLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(max_length=100)),
                ('objeto_tipo', models.CharField(max_length=100)),
                ('objeto_id', models.CharField(blank=True, max_length=100)),
                ('detalle', models.TextField(blank=True)),
                ('fecha', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'registro de auditoría',
                'verbose_name_plural': 'registros de auditoría',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('cuerpo', models.TextField()),
                ('url', models.CharField(blank=True, max_length=300)),
                ('nivel', models.CharField(choices=[('INFO', 'Informativa'), ('WARN', 'Advertencia'), ('CRIT', 'Crítica')], default='INFO', max_length=4)),
                ('leida', models.BooleanField(db_index=True, default=False)),
                ('creada', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'notificación',
                'verbose_name_plural': 'notificaciones',
                'ordering': ['-creada'],
            },
        ),
    ]
