# Generated by Django 4.2.30 on 2026-09-21 02:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cupos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Falta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.CharField(blank=True, max_length=200)),
                ('estado', models.CharField(choices=[('REGISTRADA', 'Registrada'), ('JUSTIFICADA', 'Justificada'), ('RECHAZADA', 'Justificación rechazada')], default='REGISTRADA', max_length=12)),
                ('evidencia', models.FileField(blank=True, null=True, upload_to='justificaciones/', verbose_name='evidencia')),
                ('comentario_justificacion', models.TextField(blank=True)),
                ('registrada', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('notificada', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'falta',
                'verbose_name_plural': 'faltas',
                'ordering': ['-sesion__fecha'],
            },
        ),
        migrations.CreateModel(
            name='InvitacionEvaluacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completada', models.BooleanField(default=False)),
                ('recordatorio_enviado', models.DateTimeField(blank=True, null=True)),
                ('creada', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'invitación de evaluación',
                'verbose_name_plural': 'invitaciones de evaluación',
            },
        ),
        migrations.CreateModel(
            name='PeriodoEvaluacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80)),
                ('fecha_inicio', models.DateField()),
                ('fecha_limite', models.DateField()),
                ('activo', models.BooleanField(default=False)),
                ('bloquear_servicios', models.BooleanField(default=False, verbose_name='bloquear servicios hasta evaluar (RF-31)')),
                ('umbral_participacion', models.PositiveSmallIntegerField(default=60, verbose_name='umbral mínimo de participación (%)')),
                ('preguntas', models.JSONField(blank=True, default=list)),
                ('creado', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'periodo de evaluación',
                'verbose_name_plural': 'periodos de evaluación',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='RespuestaEvaluacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntuacion', models.FloatField(verbose_name='puntuación promedio (1-5)')),
                ('comentario', models.TextField(blank=True)),
                ('respuestas_detalle', models.JSONField(blank=True, default=dict)),
                ('creado', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'respuesta de evaluación',
                'verbose_name_plural': 'respuestas de evaluación',
                'ordering': ['-creado'],
            },
        ),
        migrations.CreateModel(
            name='ResumenInasistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_sesiones', models.PositiveIntegerField(default=0)),
                ('faltas', models.PositiveIntegerField(default=0)),
                ('porcentaje', models.FloatField(default=0)),
                ('riesgo', models.CharField(choices=[('OK', 'Sin riesgo'), ('WARN', 'Advertencia'), ('CRIT', 'Riesgo crítico')], default='OK', max_length=4)),
                ('alerta_enviada', models.BooleanField(default=False)),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'resumen de inasistencia',
                'verbose_name_plural': 'resúmenes de inasistencia',
            },
        ),
        migrations.CreateModel(
            name='Sesion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(db_index=True)),
                ('tema', models.CharField(blank=True, max_length=150)),
                ('registrada', models.BooleanField(default=False)),
                ('oferta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sesiones', to='cupos.ofertacupo')),
            ],
            options={
                'verbose_name': 'sesión de clase',
                'verbose_name_plural': 'sesiones de clase',
                'ordering': ['-fecha'],
            },
        ),
    ]
