# Generated by Django 4.2.30 on 2026-09-21 02:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cupos', '0002_initial'),
        ('materias', '0001_initial'),
        ('evaluaciones', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='resumeninasistencia',
            name='estudiante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resumenes_inasistencia', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='resumeninasistencia',
            name='oferta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resumenes_inasistencia', to='cupos.ofertacupo'),
        ),
        migrations.AddField(
            model_name='respuestaevaluacion',
            name='docente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluaciones_recibidas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='respuestaevaluacion',
            name='materia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas_evaluacion', to='materias.materia'),
        ),
        migrations.AddField(
            model_name='respuestaevaluacion',
            name='periodo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='evaluaciones.periodoevaluacion'),
        ),
        migrations.AddField(
            model_name='invitacionevaluacion',
            name='docente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitaciones_recibidas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='invitacionevaluacion',
            name='estudiante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitaciones_evaluacion', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='invitacionevaluacion',
            name='materia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitaciones_evaluacion', to='materias.materia'),
        ),
        migrations.AddField(
            model_name='invitacionevaluacion',
            name='periodo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitaciones', to='evaluaciones.periodoevaluacion'),
        ),
        migrations.AddField(
            model_name='falta',
            name='estudiante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faltas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='falta',
            name='sesion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faltas', to='evaluaciones.sesion'),
        ),
        migrations.AlterUniqueTogether(
            name='sesion',
            unique_together={('oferta', 'fecha')},
        ),
        migrations.AlterUniqueTogether(
            name='resumeninasistencia',
            unique_together={('estudiante', 'oferta')},
        ),
        migrations.AlterUniqueTogether(
            name='invitacionevaluacion',
            unique_together={('periodo', 'estudiante', 'docente', 'materia')},
        ),
        migrations.AlterUniqueTogether(
            name='falta',
            unique_together={('sesion', 'estudiante')},
        ),
    ]
