# Generated by Django 4.2.30 on 2026-09-21 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('ACTIVA', 'Activa'), ('APROBADA', 'Materia aprobada'), ('CANCELADA', 'Cancelada')], default='ACTIVA', max_length=10)),
                ('confirmada', models.DateTimeField(blank=True, null=True)),
                ('creada', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'inscripción',
                'verbose_name_plural': 'inscripciones',
            },
        ),
        migrations.CreateModel(
            name='OfertaCupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo', models.CharField(db_index=True, max_length=10, verbose_name='periodo académico')),
                ('cupo_maximo', models.PositiveSmallIntegerField(verbose_name='cupo máximo')),
                ('inscritos', models.PositiveSmallIntegerField(default=0, verbose_name='inscritos')),
                ('dia', models.PositiveSmallIntegerField(default=1, verbose_name='día (1=lun ... 7=dom)')),
                ('hora_inicio', models.TimeField(default='07:00', verbose_name='hora inicio')),
                ('hora_fin', models.TimeField(default='09:00', verbose_name='hora fin')),
                ('activa', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'oferta de cupos',
                'verbose_name_plural': 'ofertas de cupos',
                'ordering': ['periodo', 'materia__codigo'],
            },
        ),
        migrations.CreateModel(
            name='SolicitudCupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('APROBADA', 'Aprobada'), ('RECHAZADA', 'Rechazada'), ('EN_ESPERA', 'En lista de espera')], default='PENDIENTE', max_length=10)),
                ('prioridad', models.FloatField(default=0, verbose_name='prioridad calculada')),
                ('justificacion_estado', models.CharField(blank=True, max_length=200)),
                ('creada', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('resuelta', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'solicitud de cupo',
                'verbose_name_plural': 'solicitudes de cupo',
                'ordering': ['-prioridad', 'creada'],
            },
        ),
    ]
