# Generated by Django 4.2.30 on 2026-09-22 19:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('materias', '0002_initial'),
        ('cupos', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Preinscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo_objetivo', models.CharField(db_index=True, max_length=10, verbose_name='periodo objetivo')),
                ('prioridad', models.PositiveSmallIntegerField(default=1, verbose_name='orden de preferencia')),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('ENVIADA', 'Enviada'), ('CONFIRMADA', 'Confirmada en oferta'), ('RECHAZADA', 'Rechazada')], default='ENVIADA', max_length=12)),
                ('probabilidad', models.FloatField(default=0, verbose_name='probabilidad de asignación (0-1)')),
                ('demanda_estimada', models.FloatField(default=0, verbose_name='demanda estimada del periodo')),
                ('franja_sugerida', models.CharField(blank=True, max_length=60, verbose_name='franja sugerida')),
                ('docentes_activos', models.PositiveSmallIntegerField(default=0, verbose_name='docentes activos')),
                ('observacion', models.CharField(blank=True, max_length=200)),
                ('creada', models.DateTimeField(auto_now_add=True)),
                ('actualizada', models.DateTimeField(auto_now=True)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preinscripciones', to=settings.AUTH_USER_MODEL)),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preinscripciones', to='materias.materia')),
            ],
            options={
                'verbose_name': 'preinscripción',
                'verbose_name_plural': 'preinscripciones',
                'ordering': ['periodo_objetivo', 'prioridad'],
                'unique_together': {('estudiante', 'materia', 'periodo_objetivo')},
            },
        ),
        migrations.CreateModel(
            name='PreferenciaPreinscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo_objetivo', models.CharField(db_index=True, max_length=10, verbose_name='periodo objetivo')),
                ('dia', models.PositiveSmallIntegerField(choices=[(1, 'Lunes'), (2, 'Martes'), (3, 'Miércoles'), (4, 'Jueves'), (5, 'Viernes'), (6, 'Sábado')], default=1, verbose_name='día (1=lun ... 6=sáb)')),
                ('franja', models.CharField(choices=[('MANANA', 'Mañana (07:00-12:00)'), ('TARDE', 'Tarde (12:00-18:00)'), ('NOCHE', 'Noche (18:00-22:00)')], default='MANANA', max_length=6)),
                ('creada', models.DateTimeField(auto_now_add=True)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preferencias_horario', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'preferencia de horario',
                'verbose_name_plural': 'preferencias de horario',
                'ordering': ['dia', 'franja'],
                'unique_together': {('estudiante', 'periodo_objetivo', 'dia', 'franja')},
            },
        ),
    ]
