# Generated by Django 4.2.30 on 2026-09-22 20:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('materias', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cupos', '0003_preinscripcion_preferenciapreinscripcion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ofertacupo',
            options={'ordering': ['periodo', 'materia__codigo', 'grupo'], 'verbose_name': 'grupo de cupos', 'verbose_name_plural': 'grupos de cupos'},
        ),
        migrations.AlterUniqueTogether(
            name='ofertacupo',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='ofertacupo',
            name='aula',
            field=models.CharField(blank=True, max_length=30, verbose_name='aula / salón'),
        ),
        migrations.AddField(
            model_name='ofertacupo',
            name='docente',
            field=models.ForeignKey(blank=True, limit_choices_to={'rol': 'DOCENTE'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grupos_dictados', to=settings.AUTH_USER_MODEL, verbose_name='docente del grupo'),
        ),
        migrations.AddField(
            model_name='ofertacupo',
            name='grupo',
            field=models.CharField(default='G1', help_text='Identificador del grupo (ej. G1, G2, NRC).', max_length=10, verbose_name='grupo / sección'),
        ),
        migrations.AddField(
            model_name='preinscripcion',
            name='grupo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preinscripciones_grupo', to='cupos.ofertacupo', verbose_name='grupo preferido'),
        ),
        migrations.AlterUniqueTogether(
            name='ofertacupo',
            unique_together={('materia', 'periodo', 'grupo')},
        ),
    ]
