# Generated by Django 4.2.30 on 2026-09-21 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NecesidadDetectada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('descripcion', models.TextField(blank=True)),
                ('origen', models.CharField(choices=[('QUEJAS', 'Quejas recurrentes'), ('CUPOS', 'Demanda insatisfecha de cupos'), ('INASISTENCIA', 'Inasistencia elevada'), ('EVALUACION', 'Evaluación docente baja'), ('MANUAL', 'Registro manual')], default='MANUAL', max_length=12)),
                ('impacto', models.CharField(choices=[('CRITICO', 'Crítico'), ('ALTO', 'Alto'), ('MEDIO', 'Medio'), ('BAJO', 'Bajo')], default='MEDIO', max_length=8)),
                ('urgencia', models.CharField(choices=[('DOCENTE', 'Docente'), ('ADMINISTRATIVA', 'Administrativa'), ('INFRAESTRUCTURA', 'Infraestructura'), ('TECNOLOGICA', 'Tecnológica')], default='DOCENTE', max_length=15)),
                ('esfuerzo', models.FloatField(default=8, verbose_name='esfuerzo estimado (horas)')),
                ('evidencia', models.JSONField(blank=True, default=dict, help_text='Métricas de respaldo (RF-52).')),
                ('score', models.FloatField(db_index=True, default=0, verbose_name='score calculado')),
                ('periodo', models.CharField(blank=True, db_index=True, max_length=10)),
                ('creada', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actualizada', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'necesidad detectada',
                'verbose_name_plural': 'necesidades detectadas',
                'ordering': ['-score', '-creada'],
            },
        ),
        migrations.CreateModel(
            name='PrediccionDemanda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo_objetivo', models.CharField(db_index=True, max_length=10)),
                ('demanda_estimada', models.FloatField(default=0)),
                ('demanda_real', models.PositiveIntegerField(blank=True, null=True)),
                ('cupo_sugerido', models.PositiveSmallIntegerField(default=0)),
                ('metodo', models.CharField(choices=[('MM', 'Promedio móvil'), ('REG', 'Regresión lineal simple'), ('HIST', 'Histórico simple')], default='MM', max_length=4)),
                ('confianza', models.FloatField(default=0, verbose_name='confianza (0-1)')),
                ('detalle', models.JSONField(blank=True, default=dict)),
                ('generada', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'predicción de demanda',
                'verbose_name_plural': 'predicciones de demanda',
                'ordering': ['-demanda_estimada'],
            },
        ),
    ]
