# Generated by Django 4.2.30 on 2026-09-21 02:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('materias', '0001_initial'),
        ('analitica', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='predicciondemanda',
            name='materia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predicciones', to='materias.materia'),
        ),
        migrations.AlterUniqueTogether(
            name='predicciondemanda',
            unique_together={('materia', 'periodo_objetivo')},
        ),
    ]
