# Generated by Django 4.2.30 on 2026-09-21 02:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlantillaReporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('tipo', models.CharField(choices=[('OCUPACION', 'Ocupación de cupos'), ('INASISTENCIA', 'Inasistencia'), ('QUEJAS', 'Quejas y tiempos de respuesta'), ('EVALUACION', 'Evaluación docente'), ('SOLICITUDES', 'Solicitudes de materia'), ('MENSAJERIA', 'Mensajería y tiempos de respuesta'), ('ACADEMICO', 'Resumen académico')], max_length=12)),
                ('descripcion', models.TextField(blank=True)),
                ('filtros', models.JSONField(blank=True, default=dict, help_text='Parámetros por defecto del reporte.')),
                ('columnas', models.JSONField(blank=True, default=list, help_text='Columnas visibles en la exportación.')),
                ('activa', models.BooleanField(default=True)),
                ('creada', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'plantilla de reporte',
                'verbose_name_plural': 'plantillas de reporte',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='ProgramacionReporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frecuencia', models.CharField(choices=[('DIARIA', 'Diaria'), ('SEMANAL', 'Semanal'), ('MENSUAL', 'Mensual')], default='SEMANAL', max_length=8)),
                ('formato', models.CharField(choices=[('PDF', 'PDF'), ('XLSX', 'Excel'), ('CSV', 'CSV')], default='CSV', max_length=4)),
                ('activa', models.BooleanField(default=True)),
                ('ultima_ejecucion', models.DateTimeField(blank=True, null=True)),
                ('proxima_ejecucion', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'programación de reporte',
                'verbose_name_plural': 'programaciones de reportes',
                'ordering': ['plantilla__nombre'],
            },
        ),
        migrations.CreateModel(
            name='ReporteGenerado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parametros', models.JSONField(blank=True, default=dict)),
                ('formato', models.CharField(choices=[('PDF', 'PDF'), ('XLSX', 'Excel'), ('CSV', 'CSV')], default='CSV', max_length=4)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('LISTO', 'Listo'), ('ERROR', 'Con error')], default='PENDIENTE', max_length=10)),
                ('archivo', models.FileField(blank=True, null=True, upload_to='reportes/')),
                ('total_registros', models.PositiveIntegerField(default=0)),
                ('contenido', models.TextField(blank=True, help_text='Caché del contenido generado (CSV).')),
                ('mensaje_error', models.CharField(blank=True, max_length=300)),
                ('creado', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('generado', models.DateTimeField(blank=True, null=True)),
                ('plantilla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reportes', to='reportes.plantillareporte')),
            ],
            options={
                'verbose_name': 'reporte generado',
                'verbose_name_plural': 'reportes generados',
                'ordering': ['-creado'],
            },
        ),
    ]
