# Generated by Django 4.2.30 on 2026-09-21 02:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reportes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='reportegenerado',
            name='solicitado_por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reportes_generados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='programacionreporte',
            name='destinatarios',
            field=models.ManyToManyField(related_name='reportes_programados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='programacionreporte',
            name='plantilla',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programaciones', to='reportes.plantillareporte'),
        ),
    ]
