# Generated by Django 6.1.1 on 2026-10-01 02:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Anuncio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('cuerpo', models.TextField(blank=True, help_text='Texto del anuncio o descripción del adjunto/enlace.')),
                ('tipo', models.CharField(choices=[('TEXTO', 'Texto'), ('IMAGEN', 'Imagen'), ('URL', 'Enlace'), ('VIDEO', 'Video'), ('DOCUMENTO', 'Documento')], default='TEXTO', max_length=10)),
                ('enlace', models.URLField(blank=True, help_text='Para tipo Enlace o Video (YouTube, Drive, etc.).', max_length=500, verbose_name='enlace')),
                ('archivo', models.FileField(blank=True, help_text='Para tipo Imagen, Video o Documento.', null=True, upload_to='anuncios/')),
                ('roles', models.CharField(blank=True, default='', help_text='Roles destino separados por coma (vacío = todos). Ej.: ESTUDIANTE,DOCENTE', max_length=120)),
                ('visible_desde', models.DateTimeField(blank=True, help_text='Opcional: inicio de la vigencia.', null=True)),
                ('visible_hasta', models.DateTimeField(blank=True, help_text='Opcional: fin de la vigencia. Vacío = sin límite.', null=True)),
                ('activo', models.BooleanField(db_index=True, default=True)),
                ('creado', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='anuncios', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'anuncio',
                'verbose_name_plural': 'anuncios',
                'ordering': ['-creado'],
            },
        ),
    ]
