# Generated by Django 6.1.1 on 2026-10-01 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anuncios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anuncio',
            name='enlace',
            field=models.URLField(blank=True, help_text='Enlace externo: URL (sitio), video (YouTube/Drive) o imagen alojada.', max_length=500, verbose_name='enlace'),
        ),
    ]
