# Generated by Django 4.2.30 on 2026-09-21 02:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('materias', '0002_initial'),
        ('mensajes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='mensaje',
            name='autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes_enviados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mensaje',
            name='hilo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes', to='mensajes.hilo'),
        ),
        migrations.AddField(
            model_name='hilo',
            name='docente',
            field=models.ForeignKey(limit_choices_to={'rol': 'DOCENTE'}, on_delete=django.db.models.deletion.CASCADE, related_name='hilos_como_docente', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='hilo',
            name='estudiante',
            field=models.ForeignKey(limit_choices_to={'rol': 'ESTUDIANTE'}, on_delete=django.db.models.deletion.CASCADE, related_name='hilos_como_estudiante', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='hilo',
            name='intervenido_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hilos_intervenidos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='hilo',
            name='materia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hilos', to='materias.materia'),
        ),
    ]
